subsystem = AOESW
component = aosq

//prefix = aoesw.aosq
modelVersion = "4.0"
title = "AO Sequencer"
wbsId = TMT.INS.AO.AOESW.AOSQ

componentType = Sequencer

description = """
The role of the AO Sequencer is to control
and coordinate the actions of the Assemblies (and sometimes HCDs) of NFIRAOS, LGSF, the OIWFS,
ODGW and rotator of the science instruments, and the AOESW RPG and PSFR.  This coordination is essential
for observing, and the tasks of starting up, shutting down, and calibrating the system are
complex enough that they warrant use of the AOSQ as well.
"""
