subsystem = AOESW
component = lgsf

description = "LGSF Sequencer commands."
receive = [
  {
    name = setState
    description = """
    Set the state of the LGSF system.

    This is not to be confused with setting the state of the laser system,
    which is one component of the LGSF state.

    The supported LGSF states are:

      * OFF: Used for planned long term down time.  In this state, all lasers
        are turned off, all the shutters and covers are closed, and all the
        mechanisms are parked and turned off.  Emergency shutdown from any state
        transitions to this state.
      * STANDBY: Power to laser system, cooling system, and electronics are
        turned on, but the mechanisms are not configured yet.  Laser shutters
        remain closed.
      * READY: the required lasers are turned on with all the shutters closed,
        the asterism generator is configured for a dedicated asterism and the
        active arrays are controlled using their LUTs. The shutter is ready to open.
      * ON-LOW: Primarily used for calibration, the laser bench low power modules
        are inserted with low power settings (~0.4W), the laser beams are
        propagated up to the BDM, and the active array loops may be closed with
        LUT (and PAC measurements if configured). This state may also be used as
        an intermediate step to transition from Ready to On.
      * ON: In this state, the lasers are turned on, the laser shutters are open,
        full power laser beams are propagated up to the BDM, and the active array
        loops are closed with LUT (and PAC measurements if configured).
      * OBSERVATION: In this state, the LLT and ACQ system covers are open, and
        the laser beams are propagated to the sky. The uplink tip/tilt (FSM)
        loops may be open or closed, depending on the AO system status.
    """
    requiredArgs = [state]
    parameters = [
      {

        name = state
        description = "configuration for LGSF "
        enum = [OFF, STANDBY, READY, ON-LOW, ON, OBSERVATION]
      }
    ]
  }
]

send = [

  //LGSF
  {
    subsystem = LGSF
    component=acq
    name=datum
  }
  {
    subsystem = LGSF
    component=las
    name=laserState
  }
  {
    subsystem = LGSF
    component=op
    name=follow
  }
  {
    // Missing - ADD 4.1
    subsystem = LGSF
    component=op
    name=park
  }
  {
    subsystem = LGSF
    component=shutter
    name=select
  }
  {
    subsystem = LGSF
    component=te
    name=lltCover
  }
  {
    // MISSING - ADD 4.1
    subsystem = LGSF
    component=te
    name=park
  }
  {
    subsystem = LGSF
    component=te
    name=follow
  }
  {
    subsystem = LGSF
    component=te
    name=asterism
  }
]

