subsystem = AOESW
component = lgsf

//prefix = aoesw.aosq
modelVersion = "4.0"
title = "LGSF Sequencer"
wbsId = TMT.INS.AO.AOESW.AOSQ

componentType = Sequencer

description = """
This is the interface of the AOESW AOSQ LGSF Sequencer.  This sequencer is used
to operate the LGSF components, primarily by handling the LGSF state transitions.
LGSF commands used for engineering and calibration routines that involve LGSF
are usually called directly by the AO Sequencer.
"""
