subsystem = AOESW
component = lgsf

publish {

  description = """
    The LGSF Sequencer publishes status information of the LGSF system.
"""

  events =[
    {
      name = state
      description = "state of LGSF"
      archive = true
      parameters = [
        {
          name = current
          description = "curret state of LGSF"
          enum = [OFF, STANDBY, READY, ON-LOW, ON, OBSERVATION]
        }

      ]
    }
  ]
}
